version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 12
  pre_build:
    commands:
      - echo Installing NPM dependencies
      - npm install
  build:
    commands:
      - echo Build started on `date`
      - npm run-script build
artifacts:
  files:
    - public/**/*
    - src/**/*
    - package.json
    - scripts/**/*